apiVersion: v1
kind: ResourceQuota
metadata:
  name: mcp-servers-quota
  namespace: mcp-servers
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 10Gi
    limits.cpu: "20"
    limits.memory: 20Gi
    pods: "100"
