[
  { "op": "add", "path": "/spec/template/spec/nodeSelector", "value": { "kubernetes.io/arch": "amd64" } },
  { "op": "add", "path": "/spec/template/spec/containers/0/resources", "value": { "requests": { "cpu": "10m", "memory": "32Mi" }, "limits": { "cpu": "100m", "memory": "128Mi" } } }
]
