import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { catchError, map } from 'rxjs/operators';

/**
 * Options for deployment requests
 */
export interface DeployOptions {
  isPrivate?: boolean;
  description?: string;
  includeDevContainer?: boolean;
  serverName?: string;
}

/**
 * URLs returned from deployment
 */
export interface DeploymentUrls {
  repository?: string;
  gist?: string;
  gistRaw?: string;
  codespace?: string;
  clone?: string;
  enterprise?: string;
}

/**
 * Response from deployment API
 */
export interface DeploymentResponse {
  success: boolean;
  deploymentId?: string;
  type?: 'gist' | 'repo' | 'enterprise' | 'none';
  urls?: DeploymentUrls;
  error?: string;
}

/**
 * Request body for deployment
 */
interface DeployRequest {
  conversationId: string;
  options?: DeployOptions;
}

@Injectable({
  providedIn: 'root'
})
export class DeploymentService {
  private readonly baseUrl = 'http://localhost:3000/api/deploy';

  constructor(private http: HttpClient) {}

  /**
   * Deploy generated MCP server to GitHub repository
   */
  deployToGitHub(conversationId: string, options?: DeployOptions): Observable<DeploymentResponse> {
    const request: DeployRequest = {
      conversationId,
      options: options || {
        isPrivate: true,
        description: 'MCP server generated by MCP Everything',
        includeDevContainer: true
      }
    };

    return this.http.post<DeploymentResponse>(`${this.baseUrl}/github`, request).pipe(
      map(response => this.transformResponse(response)),
      catchError(error => this.handleError(error, 'deployToGitHub'))
    );
  }

  /**
   * Deploy generated MCP server to GitHub Gist
   */
  deployToGist(conversationId: string, options?: DeployOptions): Observable<DeploymentResponse> {
    const request: DeployRequest = {
      conversationId,
      options: options || {
        isPrivate: true,
        description: 'MCP server generated by MCP Everything'
      }
    };

    return this.http.post<DeploymentResponse>(`${this.baseUrl}/gist`, request).pipe(
      map(response => this.transformResponse(response)),
      catchError(error => this.handleError(error, 'deployToGist'))
    );
  }

  /**
   * Get deployment status for a conversation
   */
  getDeploymentStatus(conversationId: string): Observable<DeploymentResponse[]> {
    return this.http.get<{ deployments: DeploymentResponse[] }>(
      `${this.baseUrl}/${conversationId}/status`
    ).pipe(
      map(response => response.deployments || []),
      catchError(error => this.handleError(error, 'getDeploymentStatus'))
    );
  }

  /**
   * Retry a failed deployment
   */
  retryDeployment(conversationId: string): Observable<DeploymentResponse> {
    return this.http.post<DeploymentResponse>(
      `${this.baseUrl}/${conversationId}/retry`,
      {}
    ).pipe(
      map(response => this.transformResponse(response)),
      catchError(error => this.handleError(error, 'retryDeployment'))
    );
  }

  /**
   * Transform API response to ensure consistent format
   */
  private transformResponse(response: DeploymentResponse): DeploymentResponse {
    return {
      ...response,
      urls: response.urls || {}
    };
  }

  /**
   * Handle HTTP errors
   */
  private handleError(error: HttpErrorResponse, operation: string): Observable<never> {
    console.error(`${operation} failed:`, error);

    let errorMessage = 'An unexpected error occurred';

    if (error.error instanceof ErrorEvent) {
      // Client-side error
      errorMessage = error.error.message;
    } else if (error.error?.error) {
      // Backend error with message
      errorMessage = error.error.error;
    } else if (error.error?.message) {
      // Alternative backend error format
      errorMessage = error.error.message;
    } else if (error.status === 404) {
      errorMessage = 'Conversation not found. Please ensure the MCP server was generated first.';
    } else if (error.status === 429) {
      errorMessage = 'Too many requests. Please wait a moment before trying again.';
    } else if (error.status === 500) {
      errorMessage = 'Server error during deployment. Please try again.';
    }

    return throwError(() => ({
      success: false,
      error: errorMessage
    } as DeploymentResponse));
  }
}
