/**
 * Test data for E2E tests
 */

export const TEST_MESSAGES = {
  simple: 'Generate an MCP server',
  complex: 'Generate an MCP server from the Express.js GitHub repository with full CRUD operations',
  withHtml: '<script>alert("xss")</script>',
  withSpecialChars: 'Test with special chars: <>&"\'',
  veryLong: 'This is a very long message that should test the textarea auto-resize functionality. '.repeat(10),
  multiline: 'Line 1\nLine 2\nLine 3\nLine 4\nLine 5',
  empty: '',
  whitespace: '   ',
  unicode: '🚀 Generate server with emojis 👨‍💻',
};

export const TEST_SUGGESTIONS = [
  'Generate an MCP server from a GitHub repository',
  'Create a custom MCP server from an API specification',
  'Help me understand what MCP servers can do',
];

export const MOCK_CONVERSATIONS = [
  {
    id: 'conv-1',
    sessionId: 'session-1',
    title: 'Express.js MCP Server',
    createdAt: new Date('2025-10-08T10:00:00Z'),
    updatedAt: new Date('2025-10-08T10:05:00Z'),
  },
  {
    id: 'conv-2',
    sessionId: 'session-1',
    title: 'GitHub API Integration',
    createdAt: new Date('2025-10-08T09:00:00Z'),
    updatedAt: new Date('2025-10-08T09:30:00Z'),
  },
  {
    id: 'conv-3',
    sessionId: 'session-1',
    title: 'REST API Server',
    createdAt: new Date('2025-10-08T08:00:00Z'),
    updatedAt: new Date('2025-10-08T08:15:00Z'),
  },
];

export const MOCK_MESSAGES = [
  {
    id: 'msg-1',
    conversationId: 'conv-1',
    content: 'Generate an MCP server from Express.js',
    role: 'user' as const,
    timestamp: new Date('2025-10-08T10:00:00Z'),
  },
  {
    id: 'msg-2',
    conversationId: 'conv-1',
    content: 'I\'ll help you generate an MCP server from the Express.js repository.',
    role: 'assistant' as const,
    timestamp: new Date('2025-10-08T10:00:30Z'),
  },
  {
    id: 'msg-3',
    conversationId: 'conv-1',
    content: 'MCP server generated successfully!',
    role: 'assistant' as const,
    timestamp: new Date('2025-10-08T10:05:00Z'),
  },
];

export const MOCK_SSE_EVENTS = {
  progress: {
    type: 'progress',
    message: 'Analyzing repository...',
    timestamp: new Date().toISOString(),
  },
  result: {
    type: 'result',
    message: 'I\'ll help you generate an MCP server.',
    timestamp: new Date().toISOString(),
  },
  complete: {
    type: 'complete',
    message: 'MCP server generated successfully!',
    timestamp: new Date().toISOString(),
    data: {
      generatedCode: {
        mainFile: 'index.ts',
        supportingFiles: {
          'package.json': '{"name": "test-server"}',
          'README.md': '# Test Server',
        },
      },
    },
  },
  error: {
    type: 'error',
    message: 'Failed to generate server',
    timestamp: new Date().toISOString(),
  },
};

export const MOCK_GENERATED_CODE = {
  mainFile: `import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';

const server = new Server({
  name: 'test-server',
  version: '1.0.0',
});

// Tool definitions
server.setRequestHandler('tools/list', async () => ({
  tools: [
    {
      name: 'test_tool',
      description: 'A test tool',
      inputSchema: {
        type: 'object',
        properties: {
          input: { type: 'string' }
        }
      }
    }
  ]
}));

// Start server
const transport = new StdioServerTransport();
await server.connect(transport);
`,
  supportingFiles: {
    'package.json': JSON.stringify(
      {
        name: 'test-mcp-server',
        version: '1.0.0',
        type: 'module',
        dependencies: {
          '@modelcontextprotocol/sdk': '^1.0.0',
        },
      },
      null,
      2
    ),
    'README.md': '# Test MCP Server\n\nGenerated by MCP Everything',
    'tsconfig.json': JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          module: 'Node16',
          moduleResolution: 'Node16',
        },
      },
      null,
      2
    ),
  },
};

export const API_ENDPOINTS = {
  chat: {
    message: '/api/chat/message',
    stream: (sessionId: string) => `/api/chat/stream/${sessionId}`,
  },
  conversations: {
    list: '/api/conversations',
    create: '/api/conversations',
    get: (id: string) => `/api/conversations/${id}`,
    messages: (id: string) => `/api/conversations/${id}/messages`,
    delete: (id: string) => `/api/conversations/${id}`,
    update: (id: string) => `/api/conversations/${id}`,
    deployments: (id: string) => `/api/conversations/${id}/deployments`,
    latestDeployment: (id: string) => `/api/conversations/${id}/deployments/latest`,
  },
  deploy: {
    github: '/api/deploy/github',
    gist: '/api/deploy/gist',
    status: (conversationId: string) => `/api/deploy/${conversationId}/status`,
  },
  hosting: {
    deploy: (conversationId: string) => `/api/hosting/deploy/${conversationId}`,
    servers: '/api/hosting/servers',
    server: (serverId: string) => `/api/hosting/servers/${serverId}`,
    serverStatus: (serverId: string) => `/api/hosting/servers/${serverId}/status`,
    serverLogs: (serverId: string) => `/api/hosting/servers/${serverId}/logs`,
    startServer: (serverId: string) => `/api/hosting/servers/${serverId}/start`,
    stopServer: (serverId: string) => `/api/hosting/servers/${serverId}/stop`,
  },
  health: '/health',
};

export const MOCK_DEPLOYMENT_RESPONSES = {
  githubSuccess: {
    success: true,
    deploymentId: 'deploy-github-123',
    type: 'repo',
    urls: {
      repository: 'https://github.com/testuser/mcp-server-express',
      clone: 'https://github.com/testuser/mcp-server-express.git',
      codespace: 'https://codespaces.new/testuser/mcp-server-express',
    },
    validationStatus: 'passed',
    toolsPassedCount: 3,
    toolsTestedCount: 3,
  },
  gistSuccess: {
    success: true,
    deploymentId: 'deploy-gist-456',
    type: 'gist',
    urls: {
      gist: 'https://gist.github.com/testuser/abc123def456',
      gistRaw: 'https://gist.githubusercontent.com/testuser/abc123def456/raw',
    },
    validationStatus: 'passed',
    toolsPassedCount: 3,
    toolsTestedCount: 3,
  },
  cloudSuccess: {
    success: true,
    serverId: 'server-cloud-789',
    serverName: 'mcp-express-server',
    endpointUrl: 'https://mcp-express-server.mcp.localhost',
    status: 'running',
  },
  failure: {
    success: false,
    error: 'Deployment failed: insufficient permissions or rate limit exceeded',
  },
};

export const MOCK_HOSTED_SERVERS = [
  {
    id: 'server-1',
    serverId: 'mcp-express',
    serverName: 'Express API Server',
    description: 'MCP server for Express.js applications',
    status: 'running',
    endpointUrl: 'https://mcp-express.mcp.localhost',
    tools: [
      { name: 'get_routes', description: 'Get all Express routes' },
      { name: 'add_middleware', description: 'Add middleware to app' },
    ],
    envVarNames: ['EXPRESS_PORT'],
    requestCount: 150,
    createdAt: new Date('2025-01-01T10:00:00Z').toISOString(),
    updatedAt: new Date('2025-01-02T14:30:00Z').toISOString(),
    deployedAt: new Date('2025-01-01T10:05:00Z').toISOString(),
  },
  {
    id: 'server-2',
    serverId: 'mcp-stripe',
    serverName: 'Stripe Integration',
    description: 'MCP server for Stripe payment processing',
    status: 'stopped',
    endpointUrl: 'https://mcp-stripe.mcp.localhost',
    tools: [
      { name: 'create_payment', description: 'Create a payment intent' },
      { name: 'list_customers', description: 'List Stripe customers' },
    ],
    envVarNames: ['STRIPE_API_KEY'],
    requestCount: 0,
    createdAt: new Date('2025-01-03T08:00:00Z').toISOString(),
    updatedAt: new Date('2025-01-03T08:00:00Z').toISOString(),
    stoppedAt: new Date('2025-01-03T12:00:00Z').toISOString(),
  },
  {
    id: 'server-3',
    serverId: 'mcp-github',
    serverName: 'GitHub Tools',
    description: 'MCP server for GitHub API interactions',
    status: 'failed',
    statusMessage: 'Container failed to start: missing GITHUB_TOKEN',
    endpointUrl: 'https://mcp-github.mcp.localhost',
    tools: [
      { name: 'list_repos', description: 'List repositories' },
      { name: 'create_issue', description: 'Create an issue' },
    ],
    envVarNames: ['GITHUB_TOKEN'],
    requestCount: 0,
    createdAt: new Date('2025-01-04T09:00:00Z').toISOString(),
    updatedAt: new Date('2025-01-04T09:05:00Z').toISOString(),
  },
];

export const MOCK_SERVER_LOGS = [
  '[2025-01-02T14:30:00Z] Server started on port 3000',
  '[2025-01-02T14:30:01Z] MCP server initialized with 2 tools',
  '[2025-01-02T14:30:05Z] Received request: tools/list',
  '[2025-01-02T14:30:10Z] Received request: tools/call - get_routes',
  '[2025-01-02T14:31:00Z] Health check passed',
];

export const TIMEOUTS = {
  short: 5000,
  medium: 10000,
  long: 30000,
  veryLong: 60000,
};

export const VIEWPORT_SIZES = {
  mobile: { width: 375, height: 667 },
  tablet: { width: 768, height: 1024 },
  desktop: { width: 1280, height: 720 },
  largeDesktop: { width: 1920, height: 1080 },
};
