/**
 * Test data for E2E tests
 */

export const TEST_MESSAGES = {
  simple: 'Generate an MCP server',
  complex: 'Generate an MCP server from the Express.js GitHub repository with full CRUD operations',
  withHtml: '<script>alert("xss")</script>',
  withSpecialChars: 'Test with special chars: <>&"\'',
  veryLong: 'This is a very long message that should test the textarea auto-resize functionality. '.repeat(10),
  multiline: 'Line 1\nLine 2\nLine 3\nLine 4\nLine 5',
  empty: '',
  whitespace: '   ',
  unicode: '🚀 Generate server with emojis 👨‍💻',
};

export const TEST_SUGGESTIONS = [
  'Generate an MCP server from a GitHub repository',
  'Create a custom MCP server from an API specification',
  'Help me understand what MCP servers can do',
];

export const MOCK_CONVERSATIONS = [
  {
    id: 'conv-1',
    sessionId: 'session-1',
    title: 'Express.js MCP Server',
    createdAt: new Date('2025-10-08T10:00:00Z'),
    updatedAt: new Date('2025-10-08T10:05:00Z'),
  },
  {
    id: 'conv-2',
    sessionId: 'session-1',
    title: 'GitHub API Integration',
    createdAt: new Date('2025-10-08T09:00:00Z'),
    updatedAt: new Date('2025-10-08T09:30:00Z'),
  },
  {
    id: 'conv-3',
    sessionId: 'session-1',
    title: 'REST API Server',
    createdAt: new Date('2025-10-08T08:00:00Z'),
    updatedAt: new Date('2025-10-08T08:15:00Z'),
  },
];

export const MOCK_MESSAGES = [
  {
    id: 'msg-1',
    conversationId: 'conv-1',
    content: 'Generate an MCP server from Express.js',
    role: 'user' as const,
    timestamp: new Date('2025-10-08T10:00:00Z'),
  },
  {
    id: 'msg-2',
    conversationId: 'conv-1',
    content: 'I\'ll help you generate an MCP server from the Express.js repository.',
    role: 'assistant' as const,
    timestamp: new Date('2025-10-08T10:00:30Z'),
  },
  {
    id: 'msg-3',
    conversationId: 'conv-1',
    content: 'MCP server generated successfully!',
    role: 'assistant' as const,
    timestamp: new Date('2025-10-08T10:05:00Z'),
  },
];

export const MOCK_SSE_EVENTS = {
  progress: {
    type: 'progress',
    message: 'Analyzing repository...',
    timestamp: new Date().toISOString(),
  },
  result: {
    type: 'result',
    message: 'I\'ll help you generate an MCP server.',
    timestamp: new Date().toISOString(),
  },
  complete: {
    type: 'complete',
    message: 'MCP server generated successfully!',
    timestamp: new Date().toISOString(),
    data: {
      generatedCode: {
        mainFile: 'index.ts',
        supportingFiles: {
          'package.json': '{"name": "test-server"}',
          'README.md': '# Test Server',
        },
      },
    },
  },
  error: {
    type: 'error',
    message: 'Failed to generate server',
    timestamp: new Date().toISOString(),
  },
};

export const MOCK_GENERATED_CODE = {
  mainFile: `import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';

const server = new Server({
  name: 'test-server',
  version: '1.0.0',
});

// Tool definitions
server.setRequestHandler('tools/list', async () => ({
  tools: [
    {
      name: 'test_tool',
      description: 'A test tool',
      inputSchema: {
        type: 'object',
        properties: {
          input: { type: 'string' }
        }
      }
    }
  ]
}));

// Start server
const transport = new StdioServerTransport();
await server.connect(transport);
`,
  supportingFiles: {
    'package.json': JSON.stringify(
      {
        name: 'test-mcp-server',
        version: '1.0.0',
        type: 'module',
        dependencies: {
          '@modelcontextprotocol/sdk': '^1.0.0',
        },
      },
      null,
      2
    ),
    'README.md': '# Test MCP Server\n\nGenerated by MCP Everything',
    'tsconfig.json': JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          module: 'Node16',
          moduleResolution: 'Node16',
        },
      },
      null,
      2
    ),
  },
};

export const API_ENDPOINTS = {
  chat: {
    message: '/api/chat/message',
    stream: (sessionId: string) => `/api/chat/stream/${sessionId}`,
  },
  conversations: {
    list: '/api/conversations',
    create: '/api/conversations',
    get: (id: string) => `/api/conversations/${id}`,
    messages: (id: string) => `/api/conversations/${id}/messages`,
    delete: (id: string) => `/api/conversations/${id}`,
    update: (id: string) => `/api/conversations/${id}`,
  },
  health: '/health',
};

export const TIMEOUTS = {
  short: 5000,
  medium: 10000,
  long: 30000,
  veryLong: 60000,
};

export const VIEWPORT_SIZES = {
  mobile: { width: 375, height: 667 },
  tablet: { width: 768, height: 1024 },
  desktop: { width: 1280, height: 720 },
  largeDesktop: { width: 1920, height: 1080 },
};
