import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  Index,
  ManyToOne,
  JoinColumn,
} from 'typeorm';
import { User } from './user.entity';

/**
 * MCP Server Entity
 *
 * Represents an MCP server in the marketplace. Can be:
 * - Generated by the platform (from conversations)
 * - Submitted by users
 * - Featured servers highlighted by admins
 *
 * Key relationships:
 * - author: User who created/owns the server
 * - sourceConversationId: Link to generating conversation (if platform-generated)
 *
 * Schema drift note (see 1753900010000-FixMcpServersSchemaDrift.ts):
 * the 1733500000000 migration also added CHECK (visibility/language/status IN
 * (...)) constraints that have no TypeORM representation anywhere in this
 * schema (no other enum-like column in this codebase is DB-CHECK-enforced -
 * they all rely on the TypeScript union type only, exactly like `visibility`
 * etc. here). The corrective migration deliberately drops those 3 CHECK
 * constraints for consistency rather than adding @Check decorators to
 * resurrect them: dropping loses only defense-in-depth (existing rows already
 * satisfy them; the union types still constrain writes at the app layer), and
 * keeping them would require the @Check expression text to exactly match
 * Postgres's normalized `pg_get_constraintdef` output or migration:generate
 * would perpetually flag it as changed.
 */
@Entity('mcp_servers')
export class McpServer {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ type: 'varchar', length: 100 })
  @Index('IDX_mcp_servers_name')
  name: string;

  @Column({ type: 'varchar', length: 200, unique: true })
  @Index('IDX_mcp_servers_slug')
  slug: string; // URL-friendly name (e.g., "stripe-api-server")

  @Column({ type: 'text' })
  description: string;

  @Column({ type: 'text', nullable: true })
  longDescription?: string;

  @Column({ type: 'varchar', length: 50 })
  @Index('IDX_mcp_servers_category')
  category: string; // 'api', 'database', 'utility', 'integration', etc.

  /**
   * `idx_mcp_servers_tags` is a GIN index (for array `@>`/`&&` tag search)
   * created directly in the 1733500000000 migration - TypeORM's plain
   * @Index decorator only emits btree, so it's marked synchronize:false to
   * document the index without TypeORM trying to replace it with a btree.
   */
  @Column({ type: 'text', array: true, nullable: true })
  @Index('idx_mcp_servers_tags', { synchronize: false })
  tags?: string[];

  @Column({ type: 'varchar', length: 20, default: 'public' })
  @Index('IDX_mcp_servers_visibility')
  visibility: 'public' | 'private' | 'unlisted';

  @Column({ type: 'uuid', nullable: true })
  @Index('IDX_mcp_servers_authorId')
  authorId?: string;

  @ManyToOne(() => User, { nullable: true, onDelete: 'SET NULL' })
  @JoinColumn({ name: 'authorId', foreignKeyConstraintName: 'mcp_servers_author_id_fkey' })
  author?: User;

  @Column({ type: 'varchar', length: 500, nullable: true })
  repositoryUrl?: string; // GitHub repo

  @Column({ type: 'varchar', length: 500, nullable: true })
  gistUrl?: string;

  @Column({ type: 'varchar', length: 500, nullable: true })
  downloadUrl?: string;

  /**
   * MCP Tools exposed by this server
   * Structure: [{ name: string, description: string, inputSchema: object }]
   */
  @Column({ type: 'jsonb', nullable: true })
  tools?: Array<{
    name: string;
    description: string;
    inputSchema: Record<string, unknown>;
  }>;

  /**
   * MCP Resources exposed by this server
   * Structure: [{ uri: string, name: string, description: string }]
   */
  @Column({ type: 'jsonb', nullable: true })
  resources?: Array<{
    uri: string;
    name: string;
    description: string;
  }>;

  @Column({ type: 'text', array: true, nullable: true })
  envVars?: string[]; // Required environment variables

  @Column({ type: 'varchar', length: 20, default: 'typescript' })
  language: 'typescript' | 'python' | 'javascript';

  /**
   * `idx_mcp_servers_downloads` is a DESC-ordered index created directly in
   * the 1733500000000 migration (optimized for "most downloaded" sort
   * queries) - TypeORM's @Index decorator cannot express column sort order,
   * so it's marked synchronize:false here purely to document that the index
   * exists and to stop `migration:generate` from proposing to drop it.
   */
  @Column({ type: 'integer', default: 0 })
  @Index('idx_mcp_servers_downloads', { synchronize: false })
  downloadCount: number;

  @Column({ type: 'integer', default: 0 })
  viewCount: number;

  /** See `idx_mcp_servers_downloads` above - same reasoning, DESC "top rated" sort. */
  @Column({ type: 'numeric', precision: 2, scale: 1, default: 0 })
  @Index('idx_mcp_servers_rating', { synchronize: false })
  rating: number;

  @Column({ type: 'integer', default: 0 })
  ratingCount: number;

  @Column({ type: 'varchar', length: 20, default: 'pending' })
  @Index('IDX_mcp_servers_status')
  status: 'pending' | 'approved' | 'rejected' | 'archived';

  @Column({ type: 'boolean', default: false })
  @Index('IDX_mcp_servers_featured')
  featured: boolean;

  @Column({ type: 'uuid', nullable: true })
  sourceConversationId?: string; // If generated by platform

  /**
   * Additional metadata for extensibility
   * Examples: version info, compatibility notes, prerequisites
   */
  @Column({ type: 'jsonb', nullable: true })
  metadata?: Record<string, unknown>;

  /** See `idx_mcp_servers_downloads` above - same reasoning, DESC "newest" sort. */
  @CreateDateColumn()
  @Index('idx_mcp_servers_created_at', { synchronize: false })
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;

  @Column({ type: 'timestamp', nullable: true })
  publishedAt?: Date;
}
