import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  Index,
  ManyToOne,
  JoinColumn,
} from 'typeorm';
import { User } from './user.entity';

/**
 * MCP Server Entity
 *
 * Represents an MCP server in the marketplace. Can be:
 * - Generated by the platform (from conversations)
 * - Submitted by users
 * - Featured servers highlighted by admins
 *
 * Key relationships:
 * - author: User who created/owns the server
 * - sourceConversationId: Link to generating conversation (if platform-generated)
 */
@Entity('mcp_servers')
export class McpServer {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ type: 'varchar', length: 100 })
  @Index('IDX_mcp_servers_name')
  name: string;

  @Column({ type: 'varchar', length: 200, unique: true })
  @Index('IDX_mcp_servers_slug')
  slug: string; // URL-friendly name (e.g., "stripe-api-server")

  @Column({ type: 'text' })
  description: string;

  @Column({ type: 'text', nullable: true })
  longDescription?: string;

  @Column({ type: 'varchar', length: 50 })
  @Index('IDX_mcp_servers_category')
  category: string; // 'api', 'database', 'utility', 'integration', etc.

  @Column({ type: 'text', array: true, nullable: true })
  tags?: string[];

  @Column({ type: 'varchar', length: 20, default: 'public' })
  @Index('IDX_mcp_servers_visibility')
  visibility: 'public' | 'private' | 'unlisted';

  @Column({ type: 'uuid', nullable: true })
  @Index('IDX_mcp_servers_authorId')
  authorId?: string;

  @ManyToOne(() => User, { nullable: true, onDelete: 'SET NULL' })
  @JoinColumn({ name: 'authorId' })
  author?: User;

  @Column({ type: 'varchar', length: 500, nullable: true })
  repositoryUrl?: string; // GitHub repo

  @Column({ type: 'varchar', length: 500, nullable: true })
  gistUrl?: string;

  @Column({ type: 'varchar', length: 500, nullable: true })
  downloadUrl?: string;

  /**
   * MCP Tools exposed by this server
   * Structure: [{ name: string, description: string, inputSchema: object }]
   */
  @Column({ type: 'jsonb', nullable: true })
  tools?: Array<{
    name: string;
    description: string;
    inputSchema: Record<string, unknown>;
  }>;

  /**
   * MCP Resources exposed by this server
   * Structure: [{ uri: string, name: string, description: string }]
   */
  @Column({ type: 'jsonb', nullable: true })
  resources?: Array<{
    uri: string;
    name: string;
    description: string;
  }>;

  @Column({ type: 'text', array: true, nullable: true })
  envVars?: string[]; // Required environment variables

  @Column({ type: 'varchar', length: 20, default: 'typescript' })
  language: 'typescript' | 'python' | 'javascript';

  @Column({ type: 'integer', default: 0 })
  downloadCount: number;

  @Column({ type: 'integer', default: 0 })
  viewCount: number;

  @Column({ type: 'numeric', precision: 2, scale: 1, default: 0 })
  rating: number;

  @Column({ type: 'integer', default: 0 })
  ratingCount: number;

  @Column({ type: 'varchar', length: 20, default: 'pending' })
  @Index('IDX_mcp_servers_status')
  status: 'pending' | 'approved' | 'rejected' | 'archived';

  @Column({ type: 'boolean', default: false })
  @Index('IDX_mcp_servers_featured')
  featured: boolean;

  @Column({ type: 'uuid', nullable: true })
  sourceConversationId?: string; // If generated by platform

  /**
   * Additional metadata for extensibility
   * Examples: version info, compatibility notes, prerequisites
   */
  @Column({ type: 'jsonb', nullable: true })
  metadata?: Record<string, unknown>;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;

  @Column({ type: 'timestamp', nullable: true })
  publishedAt?: Date;
}
